version: 2
updates:
  # Enable version updates for Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group patch updates together to reduce PR noise
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    # Limit to reasonable number of open PRs
    open-pull-requests-limit: 5
    # Add semantic prefix to PR titles
    commit-message:
      prefix: "deps"
      include: "scope"
    # Add labels for easier filtering
    labels:
      - "dependencies"
      - "rust"
    # Only create PRs for security updates and version updates
    # Ignore dev dependencies for patch updates to reduce noise
    ignore:
      - dependency-name: "*"
        dependency-type: "development"
        update-types: ["version-update:semver-patch"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"